YDAL 139 version 1.0 - pre PR
love-vector/yda pull request #74
Opened 2024-10-14 10:59 UTC by BogdanSynenko

2024-10-14 13:14 UTC, nktltv commented on rag/core/src/main/java/ai/yda/framework/rag/core/retriever/chunking/entity/Chunk.java
> +package ai.yda.framework.rag.core.retriever.chunking.entity;
не entity, а model. наши модели на этом уровне ни к каким сущностям не привязываются

2024-10-14 13:16 UTC, nktltv commented on rag/core/src/main/java/ai/yda/framework/rag/core/retriever/chunking/entity/Chunk.java
> + * Represents a chunk of data extracted from a document. Each chunk contains a segment of text,
`Each chunk contains a segment of text, its index in the original document, and the document's identifier.
`
Не вижу смысла перечислять поля, поторые и так видно в модели

2024-10-14 13:21 UTC, nktltv commented on rag/core/src/main/java/ai/yda/framework/rag/core/retriever/chunking/entity/Chunk.java
> + * Represents a chunk of data extracted from a document. Each chunk contains a segment of text,
допускаю, что тут я что-то недопонял, бо ещё не читал весь код

2024-10-14 13:22 UTC, nktltv commented on integrations/spring/retrievers/filesystem-retriever-starter/src/main/java/ai/yda/framework/rag/retriever/filesystem/autoconfigure/RetrieverFilesystemProperties.java
> +    private ChunkingAlgorithm chunkingAlgorithm;
Почему бы не засунуть это в RetrieverProperties?

2024-10-14 13:23 UTC, nktltv commented on integrations/spring/retrievers/filesystem-retriever-starter/src/main/java/ai/yda/framework/rag/retriever/filesystem/autoconfigure/RetrieverFilesystemProperties.java
> +    private ChunkingAlgorithm chunkingAlgorithm;
Не хватает дефолтного значения и попрошу добавить в пример javadoc выше как будет выглядеть эта настройка

2024-10-14 13:28 UTC, nktltv commented on integrations/spring/retrievers/filesystem-retriever-starter/src/main/java/ai/yda/framework/rag/retriever/filesystem/autoconfigure/RetrieverFilesystemAutoConfiguration.java
> +                filesystemProperties.getIsProcessingEnabled(),
думаю, стоит переименовать в isIndexingEnabled() и провести соотв. изменения в javadoc

2024-10-14 13:34 UTC, nktltv commented on rag/core/src/main/java/ai/yda/framework/rag/core/retriever/Indexer.java
> +public interface Indexer<DOCUMENT> {
Я не согласен с прописанным контрактом:

1. Думаю, одного метода index() пока что достаточно, пока мы не предлагаем API для её получения и обновления
2. Я вижу метод index() тем самым методом save(List<DOCUMENT> documents), который отвечает только за грамотную индексацию и не более. 
3. Не хватает интерфейса класса-обёртки, который будет выступать в роли твой реализации метода index(). В твоей реализации index() выполняет и задачи по crawling и по chunking и по processing, а этим Indexer заниматься не имеет права

2024-10-14 13:35 UTC, BogdanSynenko commented on integrations/spring/retrievers/filesystem-retriever-starter/src/main/java/ai/yda/framework/rag/retriever/filesystem/autoconfigure/RetrieverFilesystemProperties.java
> +    private ChunkingAlgorithm chunkingAlgorithm;
Да это сделаю

2024-10-14 13:37 UTC, BogdanSynenko commented on integrations/spring/retrievers/website-retriever-starter/src/main/java/ai/yda/framework/rag/retriever/website/autoconfigure/RetrieverWebsiteProperties.java
> +    private ChunkingAlgorithm chunkingAlgorithm;
Если засовывать его в RetrieverProperties в градл, надо будет прокидывать зависимость от чего-то, что я не хочу делать, ибо не уверен, нарушает ли это архитектуру.

2024-10-14 13:38 UTC, BogdanSynenko commented on integrations/spring/retrievers/filesystem-retriever-starter/src/main/java/ai/yda/framework/rag/retriever/filesystem/autoconfigure/RetrieverFilesystemAutoConfiguration.java
> +                filesystemProperties.getIsProcessingEnabled(),
Да , я тоже над эти думал но решил оставить для обсуждения тогда возвращяеи isIndexingEnabled()

2024-10-14 13:40 UTC, nktltv commented on rag/core/src/main/java/ai/yda/framework/rag/core/retriever/Indexer.java
> +package ai.yda.framework.rag.core.retriever;
По причине описаной здесь: https://github.com/love-vector/yda/pull/74/files#r1799523788, я считаю, что хранить новые сущности в пакете retriever является misleading. Да, RAG - это retrieve, augment и generate, но фреймворк, который мы строем уже отходит от минимального представления RAG. Ясное дело, что и Retriever и Indexer и Crawler и т.д. работают над эффективным получением данных, но поэтому считаю, что они могут лежать в каком-то объединяющим их по направленности пакете.

2024-10-14 13:43 UTC, nktltv commented on integrations/spring/retrievers/filesystem-retriever-starter/src/main/java/ai/yda/framework/rag/retriever/filesystem/autoconfigure/RetrieverFilesystemProperties.java
> +    private ChunkingAlgorithm chunkingAlgorithm;
Думаю, дублирование тут будет уместно, потому что Spring Developer не будет лезть глубоко внутрь, чтобы понять почему у него дефолтный алгоритм такой, как в ChunkStrategyFactory. Сетить такие значения в Properties намного прозрачнее. Ты можешь сделать как я с ExtractionConstant. Создай DEFAULT_... константы и используй их и в RetrieverProperties и в ChunkStrategyFactory

2024-10-14 13:46 UTC, nktltv commented on integrations/spring/retrievers/website-retriever-starter/src/main/java/ai/yda/framework/rag/retriever/website/autoconfigure/RetrieverWebsiteProperties.java
> +    private ChunkingAlgorithm chunkingAlgorithm;
Думаю, не так страшна доп зависимость, особенно если это core, который и так пихается везде, как дублирование property

2024-10-16 12:58 UTC, BogdanSynenko commented on rag/core/src/main/java/ai/yda/framework/rag/core/retriever/Indexer.java
> +package ai.yda.framework.rag.core.retriever;
Исправил

2024-10-17 14:59 UTC, alexSliusa submitted a review, later dismissed

2024-10-17 15:05 UTC, nktltv commented on rag/retrievers/retriever-shared/src/main/java/ai/yda/framework/rag/retriever/shared/chunking/factory/ChunkStrategyFactory.java
> +    public ChunkStrategy getStrategy(final ChunkingAlgorithm chunkingAlgorithm) {
Вот это вот всё можно красиво сделать через enum и тогда у тебя будет на 1 класс меньше

2024-10-17 15:06 UTC, nktltv requested changes
Мне очень сильно кажется, что всё, что ты добавил retriever-shared, могло бы отлично лежать в core

2024-10-17 15:08 UTC, nktltv commented on integrations/spring/retrievers/website-retriever-starter/build.gradle
> +    api project(":rag-core")
А чего ты в предыдущем build.gradle влупил shared, а сюда core?

2024-10-17 15:11 UTC, nktltv commented on rag/core/src/main/java/ai/yda/framework/rag/core/model/Chunk.java
> +public class Chunk {
Не понятно ни название класса ни javadoc. Я бы название поменял на DataChunk т.к. как у нас есть DataExtractor и DocumentData и подробнее описал javadoc, чтобы объяснить на кой оно надо и сделать сноску @see на DataExtractor или на RAG

2024-10-17 15:13 UTC, nktltv commented on rag/core/src/main/java/ai/yda/framework/rag/core/model/Chunk.java
> +public class Chunk {
Ещё ты забыл, что мы исповедуем 2 подхода инстанциирования класса - через конструктор и через билдер. Добавь, пожалуйста @Builder(toBuilder = true), а лучше @SuperBuilder(toBuilder = true)

2024-10-17 15:14 UTC, nktltv commented on rag/core/src/main/java/ai/yda/framework/rag/core/model/DocumentData.java
> + * Represents a document's content and associated metadata.
не понятно что такое документ в контекста Retriever и для чего используется эта модель

2024-10-17 15:15 UTC, nktltv commented on rag/core/src/main/java/ai/yda/framework/rag/core/model/DocumentData.java
> +package ai.yda.framework.rag.core.model;
Не уверен, что эта модель должна лежать в общих моделях RAG. Может ли это быть моделями конкретно необходимыми только для Indexer/Retriever процесса?

2024-10-17 15:17 UTC, BogdanSynenko commented on rag/retrievers/retriever-shared/src/main/java/ai/yda/framework/rag/retriever/shared/chunking/factory/ChunkStrategyFactory.java
> +    public ChunkStrategy getStrategy(final ChunkingAlgorithm chunkingAlgorithm) {
Да , на класс будет меньше но тогда разве не будет нарушена структура , ведь как по мне лучше написать один лишний класс нежели делать излишок функционала неспецыфический для класса

2024-10-17 15:17 UTC, nktltv commented on rag/core/src/main/java/ai/yda/framework/rag/core/retriever/AbstractQueryEngine.java
> +public abstract class AbstractQueryEngine extends Indexer<DocumentData> implements Retriever<RagRequest, RagContext> {
Почему написано не через generic как остальные наши интерфейсы? REQUEST extends RagRequest

2024-10-17 15:19 UTC, nktltv commented on rag/core/src/main/java/ai/yda/framework/rag/core/retriever/AbstractQueryEngine.java
> + * <p>This abstract class provides a foundation for more specialized query
Очень поверхностно, чувствуется словно ГПТ писал. Ты не мог бы скорректировать в один, но ёмкий абзац?

2024-10-17 15:21 UTC, BogdanSynenko commented on integrations/spring/retrievers/website-retriever-starter/build.gradle
> +    api project(":rag-core")
fixed

2024-10-17 15:23 UTC, BogdanSynenko commented on rag/core/src/main/java/ai/yda/framework/rag/core/model/Chunk.java
> +    public String toString() {
Просто что-бы удобно взаимдойствовать с чанками и видеть их содержимое при дибаге

2024-10-17 15:27 UTC, BogdanSynenko commented on rag/core/src/main/java/ai/yda/framework/rag/core/model/DocumentData.java
> +package ai.yda.framework.rag.core.model;
На данный момент эта моделб нужна только для Indexer/Retriever но она также определяет в каком виде передавать данные , так что я просто вынесе ее в shared

2024-10-17 15:30 UTC, nktltv commented on rag/core/src/main/java/ai/yda/framework/rag/core/retriever/Indexer.java
> +public abstract class Indexer<DOCUMENT> {
Какой смысл для Indexer выступать в роли abstract class? Если мы говорим за контракт - то метода index будет достаточно. На самом деле, как обрабатывать и куда что грузить - это не наше core`у решать. Это решать наследнику и непосредственно реализатору наследника. Ты можешь реализовать эти методы в конкретной реализации для удобства расширяемости, но не более. Ибо это уже не чёткий straightforward контракт, а контракт + сахар

2024-10-17 15:31 UTC, nktltv commented on rag/core/src/main/java/ai/yda/framework/rag/core/util/ContentUtil.java
> + * @since 0.2.0
since - это с момента когда был создан. не надо каждый раз обновлять тут версию

2024-10-17 15:32 UTC, nktltv commented on rag/core/src/main/java/ai/yda/framework/rag/core/util/ContentUtil.java
> +    public static String preprocessContent(final String content) {
Если уж на то пошло - нужно было переделать в ContentProcessingUtil или Helper и дать возможность пользователю вызывать каждый из методов типа normalizeWhitespaces или removeHtmlTags

2024-10-17 15:36 UTC, nktltv commented on rag/retrievers/retriever-shared/src/main/java/ai/yda/framework/rag/retriever/shared/chunking/factory/ChunkStrategyFactory.java
> +    public ChunkStrategy getStrategy(final ChunkingAlgorithm chunkingAlgorithm) {
Почему излишек? 

@Getter
public enum Strategy {
   SOME_STRATEGY(new SomeStrategy),
   OTHER_STRATEGY(new OtherStrategy),

  private final strat;
  
  public void doSomething() {strat.doSomething();}
}

public void met(Strategy strategy) {
   strategy.doSomething()
}

2024-10-17 15:38 UTC, nktltv commented on rag/retrievers/retriever-shared/src/main/java/ai/yda/framework/rag/retriever/shared/chunking/constants/ChunkingConstant.java
> + * These constants control chunk size limits, regular expression patterns for chunking,
Это и так видно в классе. Зачем повторяться?

2024-10-17 15:39 UTC, nktltv commented on rag/retrievers/retriever-shared/src/main/java/ai/yda/framework/rag/retriever/shared/chunking/constants/ChunkingConstant.java
> +    public static final int CHUNK_MAX_LENGTH = 1000;
Это дефолтное значение или так и надо постоянно ставить? Бо я допустим для 1-го случая писал приставку DEFAULT

2024-10-17 15:40 UTC, nktltv commented on rag/retrievers/retriever-shared/src/main/java/ai/yda/framework/rag/retriever/shared/chunking/constants/ChunkingConstant.java
> +     * This value is used to split large text into smaller chunks, ensuring that no chunk exceeds
> This value is used to split large text into smaller chunks, ensuring that no chunk exceeds

Мне кажется, это из названия понятно

2024-10-17 15:41 UTC, nktltv commented on rag/retrievers/retriever-shared/src/main/java/ai/yda/framework/rag/retriever/shared/chunking/constants/ChunkingConstant.java
> +     * This value is used to split large text into smaller chunks, ensuring that no chunk exceeds
Чтобы ты не говорил, что можно тогда всё удалить, то вот пример полезной инфы

> It is particularly useful in fixed-length chunking strategies.

2024-10-17 15:49 UTC, BogdanSynenko commented on rag/retrievers/retriever-shared/src/main/java/ai/yda/framework/rag/retriever/shared/chunking/factory/ChunkStrategyFactory.java
> +                return new FixedLengthWordChunking(ChunkingConstant.CHUNK_MAX_LENGTH);
Это было вынесено в класс ChunkingConstant. Изначально задумка стратегий чанкирования - это те стратегии, которые предоставляем мы. Они могут написать свои стратегии из-за этого. Для этих стратегий не было вынесено логики через ЛЛМ, чаты и т.д. Я изначально предполагал, что это что-то типа набора заранее сконфигурированных стратегий чанкирования, которые пользователь будет использовать без изменения при помощи простого выбора заранее заготовленной стратегии .

2024-10-17 15:55 UTC, nktltv commented on rag/core/src/main/java/ai/yda/framework/rag/core/retriever/AbstractQueryEngine.java
> +public abstract class AbstractQueryEngine extends Indexer<DocumentData> implements Retriever<RagRequest, RagContext> {
Если подумать, тут должно было быть 2 прослойки:

1. Интерфейс (от балды назову IndRiever), который объединяет Indexer и Retriever либо по средством extend либо слить в 1, но я не уверен. Думаю, лучше 2-е т.к. без index не может быть retrieve. Можно их оставить чисто как функциональные интерфейсы.
2. Класс, который включает себя (как в DefaultRag) IndRiever, Chunker и DataExtractor и определяет единый дефолтный public метод и под капотом юзает все помпоненты. Для удобства, ты можешь как раз тут написать много protected методов.

2024-10-17 15:56 UTC, BogdanSynenko commented on rag/retrievers/retriever-shared/src/main/java/ai/yda/framework/rag/retriever/shared/chunking/factory/ChunkStrategyFactory.java
> +    public ChunkStrategy getStrategy(final ChunkingAlgorithm chunkingAlgorithm) {
Я против этого, так как это нарушает минимум один принцип проектирования - "принцип единственной ответственности". Также возникнут проблемы с расширением, и этот подход не гибкий. Вместо того чтобы использовать расширяемую структуру (классы стратегий), логика "жестко" привязывается к перечислению.

2024-10-17 15:56 UTC, BogdanSynenko commented on rag/retrievers/retriever-shared/src/main/java/ai/yda/framework/rag/retriever/shared/chunking/constants/ChunkingConstant.java
> + * These constants control chunk size limits, regular expression patterns for chunking,
Завтра уберу

2024-10-17 15:56 UTC, BogdanSynenko commented on rag/retrievers/retriever-shared/src/main/java/ai/yda/framework/rag/retriever/shared/chunking/constants/ChunkingConstant.java
> + * <p>Constants like {@code CHUNK_MAX_LENGTH}, {@code REGEX_PATTERN}, and {@code WINDOW_SIZE}
Завтра уберу

2024-10-17 15:57 UTC, BogdanSynenko commented on rag/core/src/main/java/ai/yda/framework/rag/core/util/ContentUtil.java
> +    public static String preprocessContent(final String content) {
Можно и так , просто перепишу код

2024-10-17 15:57 UTC, BogdanSynenko commented on rag/core/src/main/java/ai/yda/framework/rag/core/util/ContentUtil.java
> + * @since 0.2.0
понял , изменим

2024-10-17 15:59 UTC, BogdanSynenko commented on rag/core/src/main/java/ai/yda/framework/rag/core/model/DocumentData.java
> + * Represents a document's content and associated metadata.
Это исправим

2024-10-17 15:59 UTC, BogdanSynenko commented on rag/core/src/main/java/ai/yda/framework/rag/core/retriever/AbstractQueryEngine.java
> + * <p>This abstract class provides a foundation for more specialized query
Это исправим

2024-10-17 16:00 UTC, BogdanSynenko commented on rag/core/src/main/java/ai/yda/framework/rag/core/retriever/AbstractQueryEngine.java
> + * @see Indexer
Это исправим

2024-10-17 16:03 UTC, BogdanSynenko commented on rag/retrievers/retriever-shared/src/main/java/ai/yda/framework/rag/retriever/shared/chunking/constants/ChunkingConstant.java
> +    public static final int CHUNK_MAX_LENGTH = 1000;
Это постоянное занчение , которое если и будет изменяться то только руками напрямую

2024-10-17 16:08 UTC, BogdanSynenko commented on rag/retrievers/retriever-shared/src/main/java/ai/yda/framework/rag/retriever/shared/chunking/factory/ChunkStrategyFactory.java
> +                return new FixedLengthWordChunking(ChunkingConstant.CHUNK_MAX_LENGTH);
Ну тогда пользователь обязан знать, как каждая из стратегий работает, и из очевидных стратегий можно выделить только деление по символам. И ему в любом случае придётся лезть в код и разбираться, что и как работает. Разве наша цель не состояла в том, что мы предоставляем пользователю заранее сконфигурированный инструмент в виде стратегий? Вот допустим, стратегия с Regex паттернами. Ты, как новый пользователь, сможешь написать сразу в параметрах regex паттерн, не зная, что он используется внутри?

2024-10-17 16:10 UTC, BogdanSynenko commented on rag/core/src/main/java/ai/yda/framework/rag/core/retriever/AbstractQueryEngine.java
> +public abstract class AbstractQueryEngine extends Indexer<DocumentData> implements Retriever<RagRequest, RagContext> {
Мне это нужна обдумать завтра отвечу насчёт данной идеи

2024-10-17 16:10 UTC, BogdanSynenko commented on rag/core/src/main/java/ai/yda/framework/rag/core/retriever/Indexer.java
> +public abstract class Indexer<DOCUMENT> {
Также завтра распишу для чего было принято такое решение

2024-10-17 16:31 UTC, nktltv commented on rag/retrievers/retriever-shared/src/main/java/ai/yda/framework/rag/retriever/shared/chunking/constants/ChunkingConstant.java
> +    public static final int CHUNK_MAX_LENGTH = 1000;
я знаю что такое константа. говорю, если это дефолтное значение - лучше добавить приставку, чтобы пользователь понимал, что это не какая-то прописная истина, которую обязательно нужно юзать, а стандартное значение, вместо которого можно подставить своё

2024-10-17 16:33 UTC, nktltv commented on rag/retrievers/retriever-shared/src/main/java/ai/yda/framework/rag/retriever/shared/chunking/factory/ChunkStrategyFactory.java
> +                return new FixedLengthWordChunking(ChunkingConstant.CHUNK_MAX_LENGTH);
через properties, где ты уже указал DEFAULT_REGEX_PATTERN для это стратегии, иначе юзер может задать свой. а если не указан - юзается твой дефолтный

2024-10-18 07:01 UTC, nktltv commented on rag/retrievers/retriever-shared/src/main/java/ai/yda/framework/rag/retriever/shared/chunking/factory/ChunkStrategyFactory.java
> +    public ChunkStrategy getStrategy(final ChunkingAlgorithm chunkingAlgorithm) {
Логика выбора? Этот подход её полностью закрывает. Это по-сути и есть твоя фабрика просто реализованная через enum

2024-10-27 15:53 UTC, closed without merging